### ISSUE TITLE
Issue accessing monitor?

### ISSUE THREAD

**Issue by pcleary00** [NFLabs/ansible-hadoop#8]
I ran this playbook against an openstack tenant I have.

First, great job.  I was able to run the playbook successfully with a few small issues.  Namely, I needed to disable requiretty in sudoers and updated the playbook.

So, the install ran successfully, at least that is what it appears.

When I go to try and access the "monitor", I cannot see it.

If I go onto the monitor VM and run a `curl`, I do get a "Welcome to NGINX" page.

Could this perhaps be due to iptables?  The source range I put in only encompassed the servers that were setup, the iptables source range does not include my laptop's ip.

Wondering if there are any other things to look for?

**Comment by anthonycorbacho** [comment]
Hi @pcleary00 

Currently, the monitor roles is not available, I am working on it and will be able to pr it really soon.

Then you will be able to update your cluster by calling the deploy like: `./deploy monitor`

I will let you know when this will be done.

**Comment by anthonycorbacho** [comment]
I started the PR #9

**Comment by pcleary00** [comment]
Thanks for the update!

I am still curious as to why I can't see the nginx default html page.

When I ssh onto the monitor vm, and run `curl -v http://monitor`, I see:

```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

But I cannot access that remotely.  Any ideas?

**Comment by pcleary00** [comment]
One more update, I can indeed run that curl from other machines in the cluster, just not remotely.

Thinking this has to do with iptables

I have never setup a spark cluster before, why do I need iptables configured?

Thanks for your help!

**Comment by anthonycorbacho** [comment]
@pcleary00, Yes you must open the port of the vm or add your IP to the ip range
(something like: `-A INPUT -s __YOUR_IP__/32 -j ACCEPT`)
